// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVWdEmyOsfxezbzqH0TS9XkO6hvqFWWxE',
    appId: '1:337215195382:web:494e1dd10a28cbfadf44d7',
    messagingSenderId: '337215195382',
    projectId: 'insta-clone-4403f',
    authDomain: 'insta-clone-4403f.firebaseapp.com',
    storageBucket: 'insta-clone-4403f.appspot.com',
    measurementId: 'G-06KNEPWY9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKnP79VKVAk4ZkvwDyou8ClmH0YI0pvnU',
    appId: '1:337215195382:android:572cf26115a76992df44d7',
    messagingSenderId: '337215195382',
    projectId: 'insta-clone-4403f',
    storageBucket: 'insta-clone-4403f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS9cnDnSVsPGQ7lkfR4dJq7klX3VCecNQ',
    appId: '1:337215195382:ios:36db3c8a3fd241c8df44d7',
    messagingSenderId: '337215195382',
    projectId: 'insta-clone-4403f',
    storageBucket: 'insta-clone-4403f.appspot.com',
    iosBundleId: 'com.example.valoAccounts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS9cnDnSVsPGQ7lkfR4dJq7klX3VCecNQ',
    appId: '1:337215195382:ios:640f99ebd0b5e217df44d7',
    messagingSenderId: '337215195382',
    projectId: 'insta-clone-4403f',
    storageBucket: 'insta-clone-4403f.appspot.com',
    iosBundleId: 'com.example.valoAccounts.RunnerTests',
  );
}
